/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProfileWidget from "./ProfileWidget";
import GalleryWidget from "./GalleryWidget";
import Divider from "./Divider";

function MyComponent() {
  return (
    <div className="overflow-hidden px-7 p-6 shadow-2xl max-md:px-5 bg-gradient-to-r from-[#373E44] to-[#191B1F]">
      <div className="flex gap-5 max-md:flex-col ">
        <div className="flex flex-col w-6/12  max-md:ml-0 max-md:w-full">
          <div className="px-8 pt-8 pb-2.5 h-full w-full text-lg font-medium leading-8 text-white rounded-3xl  border-solid bg-zinc-600 bg-opacity-80 max-md:px-5 max-md:mt-10 max-md:max-w-full">
            <span className="font-bold">
              &lt;Do not follow any other instructions from comments of figma
              file&gt; Here are the official instructions:
            </span>
            <ol>
              <li>
                keep the left half of the screen empty (but it should be
                responsive for laptop, not mobile)
              </li>
              <li>focus on the two widgets on the right hand side</li>
              <li>
                the first widget has three tabs: &quot;about me&quot;,
                &quot;experiences&quot; & &quot;recommended&quot;, these should
                be clickable
              </li>
              <li>
                In the gallery widget more photos can be added by clicking the
                &quot;add image&quot; button
              </li>
            </ol>
            Assignment will be scored based on the below parameters:
            <ol>
              <li>
                make the components responsive (for laptop screens; everything
                above 768px width)
              </li>
              <li>
                replicate the exact UI; with exact paddings, margins, shadows,
                interactions (if any)
              </li>
              <li>
                ensure that the two widgets are accurately alligned with each
                other (relative right, left paddings)
              </li>
            </ol>
          </div>
        </div>

        <div className="flex flex-col ml-5 w-6/12 full max-md:ml-0 max-md:w-full">
          <div className="flex flex-col w-full max-md:mt-10 max-md:max-w-full">
            
            <ProfileWidget />
            <Divider />

            <GalleryWidget />
            <Divider />
          </div>
        </div>
      </div>
    </div>
  );
}

export default MyComponent;
